Features/amal
radicleart/fe-sticksnstones pull request #10
Opened 2021-07-28 15:50 UTC by amalkahsay

-done about page 
-changed the text colour on the admin page 
-started working on the security and Privacy pages + Q&A

2021-07-29 15:43 UTC, simonesquad commented on src/views/About.vue
> +  props: ['about'],
These props should be 'content' to match the computed and how it is called in the component above.

2021-07-29 15:43 UTC, simonesquad commented on src/views/About.vue
> +  name: 'about',
This is fine as just the name of the component.

2021-07-29 18:02 UTC, simonesquad commented on src/views/About.vue
> +      const content = this.$store.getters['contentStore/getAbout']
The only thing I would say here is that I believe there is KEY already made in APP_CONSTANTS for this.

2021-07-29 18:03 UTC, simonesquad commented on src/views/About.vue
> +      const content = this.$store.getters['contentStore/getAbout']
@amalkahsay

2021-07-30 18:48 UTC, amalkahsay commented
Q&A/Terms and services pages are running, need to add more content an… …
0a8a006
…d link them to each other

2021-08-09 10:39 UTC, ThomasLefebvreCS requested changes
Great progress Amal, still a few things to change : 
- Some pages don't have a good name (QandA -> faq, security -> Terms and conditions)
- The paths /all, /minted etc already exist, so you don't have to add them to the router. They are part of the /my-items page.
- Some minor design/UI problems still exist

2021-08-09 10:39 UTC, ThomasLefebvreCS commented on src/router/index.ts
> +    path: '/all',
I think this (and all the following path) are wrong : indeed, they refer to some under pages of the /my-items page. Then their path shouldn't just be /all, /minted etc.
Here, it created empty useless pages. You can see them by going on http://localhost:8086/all.

2021-08-09 10:39 UTC, ThomasLefebvreCS commented on src/views/Security.vue
> +  name: 'Security',
Why is it called security if it is the Term and conditions page ?

2021-08-09 10:39 UTC, ThomasLefebvreCS commented on src/views/QAndA.vue
> +  name: 'qanda',
Should be called faq

2021-08-09 10:39 UTC, ThomasLefebvreCS commented on src/views/About.vue
> +      <a title="join us on discord" href="https://discord.com/invite/sQaKVft" class="mr-4"><b-button variant="light">Button</b-button>
Why is this discord link called "Button" ? :smile:

2021-08-19 17:42 UTC, closed without merging